forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma/epel'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/postgresql'
mod 'crayfishx/firewalld'
mod 'mthibaut/users'
mod 'jlambert121/trusted_ca'
mod 'OpenConceptConsulting/nslcd'

mod 'ebrc/ebrc_yum_repo',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_yum_repo.git'

mod 'ebrc/irods',
  :git => 'git@github.com:EuPathDB/puppet-irods.git'

mod 'local/profiles',
  :path => './src/profiles'
  :latest
